version: "3.3"

services:
  app:
    container_name: azure_ad_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/logs
